# -*- coding: utf-8 -*-
"""Project ATM 5 methods OOP Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12yAudB9ImYcZd79qyqtvTN2isSyuIZGa
"""

class atm:
    def __init__(self, name,account_num,branch, pin, balance):
        self.name = name
        self.account_num = account_num
        self.branch = branch
        self.pin = pin
        self.balance = balance

    def __str__(self):
        return "This is ATM programing"

    def info (self):
        print(f"""
        -------------------------------------------------------------
        Name: {self.name}
        Number: {self.account_num}
        Branch: {self.branch}
        Balance: {self.balance} baht
        If your information wrong please contact us 00-101-001002
        -------------------------------------------------------------""")
    
    def deposit(self, amount):
        self.amount = amount
        self.balance += amount
        print(f"""
        ---------------------------------------
        Deposit: {amount} baht
        Current balance: {self.balance} baht
        ---------------------------------------""")

    def withdraw(self, amount):
        self.amount = amount
        self.balance -= amount
        print(f"""
        ---------------------------------------
        Withdraw: {amount} baht
        Current balance: {self.balance} baht
        ---------------------------------------""")

    def check(self):
        print(f"""Current balance: {self.balance} baht""")
    
    def otp(self):
        import random
        number =  random.randint(1000, 9999)
        print(f"""
        {number} is your ATM OTP.
        Do not share it with anyone""")

    def log_in(self):
        n = 0
        while (n<3):

            insert_pin = input(f"Please fill you pin: ")
            if self.pin == insert_pin:
                print("Logging in")
                break
            else:
                n += 1 
                print("Your pin is incorrect")    

    def transfer(self):
        while True:
            acc_des = input("Select Bank: ")
            acc_des_num = int(input("Account Number: "))
            amount = int(input("Transfer amount: "))
            if amount > self.balance:
                print("not enoungh money")
            else:
                self.balance -= amount
                print(f"""
                +++++++++Transfer complete++++++++++
                ------------------------------------
                   Bank: {acc_des}                  
                   Account number: {acc_des_num}   
                   Tranfer amount: {amount} baht        
                   Current Balance: {self.balance} baht  
                ------------------------------------
                ++++++++Thank you for visit us+++++++""")
                break



ppl1 = atm("Tony","888-8383-888", "Brooklyn","1234",1000)
ppl2 = atm("Mary","999-9304-985", "Ginza","2345",2000)

ppl1.log_in()
ppl1.check()
ppl1.deposit(25000)
ppl1.withdraw(5000)
ppl1.info()
ppl1.otp()

ppl1.transfer()